// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/modules/signup/data/repositories/signup_with_email_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/modules/login/data/models/user_model.dart' as _i2;
import 'package:todo_app/modules/signup/data/data_sources/i_signup_data_source.dart'
    as _i3;
import 'package:todo_app/modules/signup/domain/use_cases/signup_with_email.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [ISignupDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignupDataSource extends _i1.Mock implements _i3.ISignupDataSource {
  MockISignupDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> signupWithEmail(_i5.Params? params) =>
      (super.noSuchMethod(Invocation.method(#signupWithEmail, [params]),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
}
