// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/modules/signup/domain/use_cases/signup_with_email_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/core/errors/errors.dart' as _i5;
import 'package:todo_app/modules/login/domain/entities/user.dart' as _i6;
import 'package:todo_app/modules/signup/domain/repositories/i_signup_repository.dart'
    as _i3;
import 'package:todo_app/modules/signup/domain/use_cases/signup_with_email.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ISignupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignupRepository extends _i1.Mock implements _i3.ISignupRepository {
  MockISignupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> signupWithEmail(
          _i7.Params? params) =>
      (super.noSuchMethod(Invocation.method(#signupWithEmail, [params]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.User>>.value(
                  _FakeEither_0<_i5.Failure, _i6.User>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);
}
