// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/modules/tasks/data/repositories/task_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/modules/tasks/data/interfaces/i_task_provider.dart'
    as _i3;
import 'package:todo_app/modules/tasks/domain/dtos/create_task_dto.dart' as _i5;
import 'package:todo_app/modules/tasks/domain/entities/task.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTask_0 extends _i1.Fake implements _i2.Task {}

/// A class which mocks [ITaskProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskProvider extends _i1.Mock implements _i3.ITaskProvider {
  MockITaskProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Task>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i2.Task>>.value(<_i2.Task>[]))
          as _i4.Future<List<_i2.Task>>);
  @override
  _i4.Future<_i2.Task> create(_i5.CreateTaskDto? dto) =>
      (super.noSuchMethod(Invocation.method(#create, [dto]),
              returnValue: Future<_i2.Task>.value(_FakeTask_0()))
          as _i4.Future<_i2.Task>);
}
