// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/modules/auth/domain/use_cases/log_in_with_email_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/core/errors/errors.dart' as _i5;
import 'package:todo_app/modules/auth/domain/dtos/log_in_dto.dart' as _i7;
import 'package:todo_app/modules/auth/domain/entities/user.dart' as _i6;
import 'package:todo_app/modules/auth/domain/interfaces/i_log_in_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ILogInRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILogInRepository extends _i1.Mock implements _i3.ILogInRepository {
  MockILogInRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> logInWithEmail(
          _i7.LogInDto? dto) =>
      (super.noSuchMethod(Invocation.method(#logInWithEmail, [dto]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.User>>.value(
                  _FakeEither_0<_i5.Failure, _i6.User>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);
}
