// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/modules/home/data/repositories/task_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/modules/home/data/data_sources/i_task_data_source.dart'
    as _i2;
import 'package:todo_app/modules/home/domain/entities/task.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ITaskDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskDataSource extends _i1.Mock implements _i2.ITaskDataSource {
  MockITaskDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Task>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i4.Task>>.value(<_i4.Task>[]))
          as _i3.Future<List<_i4.Task>>);
}
