// Mocks generated by Mockito 5.1.0 from annotations
// in todo_app/test/modules/sign_up/data/repositories/sign_up_with_email_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/modules/login/data/models/user_model.dart' as _i2;
import 'package:todo_app/modules/sign_up/data/data_sources/i_sign_up_data_source.dart'
    as _i3;
import 'package:todo_app/modules/sign_up/domain/dtos/sign_up_dto.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [ISignUpDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignUpDataSource extends _i1.Mock implements _i3.ISignUpDataSource {
  MockISignUpDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> signUpWithEmail(_i5.SignUpDto? dto) =>
      (super.noSuchMethod(Invocation.method(#signUpWithEmail, [dto]),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
}
